import Head from 'next/head'
import Image from 'next/image'
import Container from '@components/Container'
import Button from '@components/Button'
import Header from '@components/Header'
import styles from '@styles/Home.module.scss'
import products from '@data/products.json'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Header/>
      <main className={styles.main}>
        <Container>
          <h1>Shoesh Snkrs</h1>
          <h2>Available Shoes</h2>
          <ul className={styles.products}>
            {products.map(product => {
              return(
                <li key={product.id}>
                  <Image width="2048" height="1228" src={product.image} alt={`Sneaker of ${product.title}`} />
                  <h3 className={styles.productsTitle}>{product.title}</h3>
                  <p className={styles.productsPrice}>{product.price}</p>
                  <Button>Add to cart</Button>
                </li>
              )
            })}  
          </ul> 
        </Container>
      </main>

      <footer className={styles.footer}>
       &copy; Shoesh Snkrs, 2021
      </footer>
    </div>
  )
}
