import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import Container from '@components/Container'
import Button from '@components/Button'
import Header from '@components/Header'
import styles from '@styles/Home.module.scss'
import products from '@data/products.json'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://app.snipcart.com"/>
        <link rel="preconnect" href="https://cdn.snipcart.com"></link>
        <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.2.1/default/snipcart.css" />
      </Head>


      <Header/>
      <main className={styles.main}>
        <Container>
          <h1>Shoesh Snkrs</h1>
          <h2>Available Shoes</h2>
          <ul className={styles.products}>
            {products.map(product => {
              return(
                <li key={product.id}>
                  <Image width="2048" height="1228" src={product.image} alt={`Sneaker of ${product.title}`} />
                  <h3 className={styles.productsTitle}>{product.title}</h3>
                  <p className={styles.productsPrice}>{product.price}</p>
                  <Button
                  className="snipcart-add-item"
                  data-item-id={product.id}
                  data-item-price={product.price}
                  data-item-url="/"
                  data-item-description=""
                  data-item-image={product.image}
                  data-item-name={product.title}
                  >Add to cart</Button>
                </li>
              )
            })}  
          </ul> 
        </Container>
      </main>

      <footer className={styles.footer}>
       &copy; Shoesh Snkrs, {new Date().getFullYear()}
      </footer>
      <Script  src="https://cdn.snipcart.com/themes/v3.2.1/default/snipcart.js"></Script>
      <div hidden id="snipcart" data-api-key={process.env.NEXT_PUBLIC_SNIPCART_API_KEY}></div>
    </div>
  )
}
